name: weather_api_dio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  json_serializable: ^6.9.5
  lottie: ^2.6.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  envied: ^1.1.1
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter_lints: ^5.0.0
envied_generator: ^1.1.1
build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
  - .env